# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: /
    weight: 10
  - name: Experince
    url: experience/
    weight: 11
  - name: Blog (Soon)
    url: /
    weight: 12
  - name: Projects (Soon)
    url: /
    weight: 13
  - name: Resources (Soon)
    url: /
    weight: 20
  - name: News (Soon)
    url: /
    weight: 30
  - name: Contact info (Soon)
    url: /
    weight: 40
